[changelog]
header = """
# Changelog
"""
body = """
{%- macro remote_url() -%}
  https://github.com/jpnurmi/slope
{%- endmacro -%}

{% if version -%}
## {{ version | trim_start_matches(pat="v") }}
{% else -%}
## Unreleased
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first | trim }}\
{% endfor %}
{% endfor -%}
"""
trim = false

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
  { message = "^feat", group = "<0>Features" },
  { message = "^fix", group = "<1>Fixes" },
  { message = "^(doc|perf|ref)", group = "<2>Improvements" },
  { message = "^(build|chore)\\(deps\\)", group = "<3>Dependencies" },
  { message = "^(build|ci|chore|test)", skip = true },
]
